// <auto-generated />
namespace Stipendia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GroupId_in_Scholarship : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GroupId_in_Scholarship));
        
        string IMigrationMetadata.Id
        {
            get { return "201704161919163_GroupId_in_Scholarship"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
